{
    "name": "Dugeons & Dragons",
    "version": "1.0",
    "category": "Extra Tools",
    "summary": "Dugeons & Dragons",
    "description": "Dugeons & Dragons",
    "author": "Espadas",
    "website": "",
    "depends": ["base", "website"],
    "data": [
        "security/ir.model.access.csv",
        "views/dd_actions.xml",
        "views/dd_menus.xml",
        "views/views_dd_character.xml",
        "views/views_dd_class.xml",
        "views/views_dd_equipment.xml",
        "views/views_dd_quest.xml",
        "views/views_dd_skill.xml",
        "views/views_dd_monster.xml",
        "src/xml/create_character_template.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": True,
}
